### ISSUE TITLE
No Locks created

### ISSUE THREAD

**Issue by retoziegler** [Danielhiversen/home_assistant_petcare#8]
When adding this integration either via UI or config.yaml, it only generates two sensors (one for the hub and one for the cat) - there are no locks created. There are no entries in the logs.

**Comment by Danielhiversen** [comment]
Could you enable debug logging?

```

logger:
  default: warning
  logs:
    custom_components.petcare: debug


```
